const express=require("express");
const bodyParser=require("body-parser");
const cors=require("cors");
const {mongoose}=require("./db.js");
const brandcontroller=require("../Backend/contollers/brandController");
const categorycontroller=require("../Backend/contollers/categoryController");
const Subcategorycontroller=require("../Backend/contollers/subcategoryController");
const childSubcategorycontroller=require("../Backend/contollers/childSubcategoryController");
const productcontroller=require("../Backend/contollers/productsController");
const variantcontroller=require("../Backend/contollers/variantController");
const variantoptioncontroller=require("../Backend/contollers/variantoptionController");
const optionvaluecontroller=require("../Backend/contollers/optionvalueController");
const proskucontroller=require("../Backend/contollers/proskuController");
const prosalecontroller=require("../Backend/contollers/prosaleController");
const usercontroller=require("../Backend/contollers/userController");
const logincontroller=require("../Backend/contollers/loginController");
var app=express();
app.use(bodyParser.json());
// app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
app.use(cors({origin:'http://localhost:4200'}));
app.listen(8080,()=>console.log("server started at port 8080"));

app.use("/brand",brandcontroller);
app.use("/category",categorycontroller);
app.use("/subcategory",Subcategorycontroller);
app.use("/childsubcategory",childSubcategorycontroller);
app.use("/product",productcontroller);
app.use("/variant",variantcontroller);
app.use("/option",variantoptioncontroller);
app.use("/optionvalue",optionvaluecontroller);
app.use("/prosku",proskucontroller);
app.use("/prosale",prosalecontroller);
app.use("/user",usercontroller);
app.use("/login",logincontroller);